### ISSUE TITLE
[wireguard_peer] Problems adding multiple peers

### ISSUE THREAD

**Issue by mnlhfr** [O-X-L/ansible-opnsense#25]
## Basic info

- [X] Affected Module: WireGuard

### Versions
* Controller
  - [X] Collection version: ansibleguy.opnsense           1.2.3
  - [X] Ansible & Python version:
```
ansible [core 2.15.1]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

* OPNSense
  - [X] System version: 23.1.10_1-amd64
  - [X] Plugin version: 1.13_5

### Describe the bug
I have an inventory group with 4 wireguard clients defined which I am trying to add as peers on opnsense.
Ansible reports all 4 added, however with each run of the playbook, only the first host is added.

So for example:
When no peers from the inventory exist on opnsense, this is the output of ansible:
```
TASK [add peer on opnsense] ***************************
changed: [host1 -> localhost]
changed: [host2 -> localhost]
changed: [host3 -> localhost]
changed: [host4 -> localhost]
```
Inspecting the actual opnsense config, i can see that host1 was successfully created, but all others are missing.

Without changing anything in the opnsense web gui, i run the playbook again and get this output:
```
TASK [add peer on opnsense] ***************************
ok: [host1 -> localhost]
changed: [host2 -> localhost]
changed: [host3 -> localhost]
changed: [host4 -> localhost]
```

Now it recognizes that host1 already exists and creates the remaining 3. Inspecting the web ui again, i can see that now host1 and host2 exist, but host3 and host4 are still missing.

So every time I run the playbook it really only creates 1 peer.

~~I suspect this has something to do with the reload/save mechanism on opnsense~~

~~I feel like this might be an issue on the OpnSense API side, since the debug output from the plugin looks ok to me.~~
~~But on the other hand I can't be the first person to run into this and couldn't find anything on this issue~~

~~Is there some sort of trick to still be able to use this plugin for this use-case? Am I missing something?~~

I tried to reproduce this behavior for better debugging on the OpnSense side with a simple python script that creates some hosts and gets a list of all peers inbetween each call to `/api/wireguard/client/addClient` (see bottom of this post) and i am not able to reproduce the issue this plugin seems to be facing. Is it possible that ansible caches the responses from `/api/wireguard/client/get` ? Am i using the plugin wrong somehow?

### Expected behavior

all 4 hosts get added as peer

### Debug output
Output for host3, when host1 and host2 already exist.
```
[WARNING]: RESPONSE: '{'status_code': 200, 'headers': Headers({'content-type': 'application/json; charset=UTF-8', 'cache-control': 'max-age=180000', 'accept-ranges': 'bytes', 'content-length': '1503', 'date': 'Fri, 28
Jul 2023 21:43:24 GMT', 'server': 'OPNsense'}), '_request': <Request('GET', 'https://XXXXXXXXXXXXXXXXXX/api/wireguard/client/get')>, 'next_request': None, 'extensions': {'http_version': b'HTTP/1.1', 'reason_phrase': b'OK',
'network_stream': <httpcore._backends.sync.SyncStream object at 0x7fe08acc3c10>}, 'history': [], 'is_closed': True, 'is_stream_consumed': True, 'default_encoding': 'utf-8', 'stream': <httpx._client.BoundSyncStream
object at 0x7fe08acc08b0>, '_num_bytes_downloaded': 1503, '_decoder': <httpx._decoders.IdentityDecoder object at 0x7fe08acc2fe0>, '_elapsed': datetime.timedelta(microseconds=265281), '_content': b'{"client":{"clients":
{"client":{"25854852-e33e-471e-b5ac-
40da89064eb8":{"enabled":"1","name":"some-host","pubkey":"XXXXXXXXXXXXXXXXXX","psk":"","tunneladdress":{"10.10.10.21\\/32":{"value":"10.10.10.21\\/32","selected":1}},"serveraddress":"","serverpo
rt":"","keepalive":""},"e3da4828-7ded-4f47-9b41-
804c70f5b01b":{"enabled":"1","name":"another-host","pubkey":"XXXXXXXXXXXXXXXXXX","psk":"","tunneladdress":{"10.0.10.0\\/24":{"value":"10.0.10.0\\/24","selected":1},"XXXXXXXXXXXXXXXXXX":{"val
ue":"XXXXXXXXXXXXXXXXXX","selected":1}},"serveraddress":"XXXXXXXXXXXXXXXXXX","serverport":"51820","keepalive":""},"f79c8486-e12c-4fb2-aae7-
4e723ee22a9b":{"enabled":"1","name":"and-another-host-that-has-nothing-to-do-with-this","pubkey":"XXXXXXXXXXXXXXXXXX","psk":"","tunneladdress":{"10.10.10.20\\/32":{"value":"10.10.10.20\\/32","selected":1}},"serveraddress":"","serverp
ort":"","keepalive":""},"52413188-fe7d-4873-b724-174fa73248e7":{"enabled":"1","name":"host1","pubkey":"XXXXXXXXXXXXXXXXXX","psk":"","tunneladdress":{"10.10.11.12\\/32":{"value":"10.10.11.12\\/32","selected":1}},"serveraddress":"XXXXXXXXXXXXXXXXXX","serverport":"51820","keepalive":"
25"},"64dcca12-f264-4cd1-bee2-d4e4b38da9d4":{"enabled":"1","name":"host2","pubkey":"XXXXXXXXXXXXXXXXXX=","psk":"","tunneladdress":{"10.10.11.13\\/32":{"value":"10.10.11.13\\/32","selected":1}},"serveraddress":"XXXXXXXXXXXXXXXXXX","serverport":"51820","keepalive":"25"}
}}}}'}'
[WARNING]: NOT MATCHING: 'some-host' != 'host3'
[WARNING]: NOT MATCHING: 'another-host' != 'host3'
[WARNING]: NOT MATCHING: 'and-another-host-that-has-nothing-to-do-with-this' != 'host3'
[WARNING]: NOT MATCHING: 'host1' != 'host3'
[WARNING]: NOT MATCHING: 'host2' != 'host3'
[WARNING]: REQUEST: POST | URL: https://XXXXXXXXXXXXXXXXXX/api/wireguard/client/addClient | HEADERS: '{'Content-Type': 'application/json'}' | DATA: '{"client": {"name": "host3", "enabled": 1, "pubkey":
"XXXXXXXXXXXXXXXXXX", "psk": "", "serverport": "51820", "tunneladdress": "10.10.11.11/32", "serveraddress": "XXXXXXXXXXXXXXXXXX", "keepalive": "25"}}'
[WARNING]: RESPONSE: '{'status_code': 200, 'headers': Headers({'content-type': 'application/json; charset=UTF-8', 'content-length': '64', 'date': 'Fri, 28 Jul 2023 21:43:25 GMT', 'server': 'OPNsense'}), '_request':
<Request('POST', 'https://XXXXXXXXXXXXXXXXXX/api/wireguard/client/addClient')>, 'next_request': None, 'extensions': {'http_version': b'HTTP/1.1', 'reason_phrase': b'OK', 'network_stream':
<httpcore._backends.sync.SyncStream object at 0x7fe08acc3c10>}, 'history': [], 'is_closed': True, 'is_stream_consumed': True, 'default_encoding': 'utf-8', 'stream': <httpx._client.BoundSyncStream object at
0x7fe08acc2b60>, '_num_bytes_downloaded': 64, '_decoder': <httpx._decoders.IdentityDecoder object at 0x7fe08acc3130>, '_elapsed': datetime.timedelta(microseconds=226650), '_content':
b'{"result":"saved","uuid":"82a81321-b148-441a-821e-ad5e7a5bdfb4"}'}'
[WARNING]: RESPONSE: '{'status_code': 200, 'headers': Headers({'content-type': 'application/json; charset=UTF-8', 'content-length': '15', 'date': 'Fri, 28 Jul 2023 21:43:30 GMT', 'server': 'OPNsense'}), '_request':
<Request('POST', 'https://XXXXXXXXXXXXXXXXXX/api/wireguard/service/reconfigure')>, 'next_request': None, 'extensions': {'http_version': b'HTTP/1.1', 'reason_phrase': b'OK', 'network_stream':
<httpcore._backends.sync.SyncStream object at 0x7fe08acc3c10>}, 'history': [], 'is_closed': True, 'is_stream_consumed': True, 'default_encoding': 'utf-8', 'stream': <httpx._client.BoundSyncStream object at
0x7fe08acc09a0>, '_num_bytes_downloaded': 15, '_decoder': <httpx._decoders.IdentityDecoder object at 0x7fe08acc25f0>, '_elapsed': datetime.timedelta(seconds=4, microseconds=642319), '_content': b'{"status":"ok"}'}'
```

### Tasks
Task(s) that produce the error:

```yaml
    - name: add peer on opnsense
      ansibleguy.opnsense.wireguard_peer:
        name: '{{ inventory_hostname }}'
        allowed_ips: '{{ wireguard_address }}'
        endpoint: '{{ ansible_host }}'
        port: '{{ wireguard_listenport | default(51820) }}'
        public_key: '{{ pubkey }}'
        keepalive: 25
        enabled: true
        debug: false
        state: 'present'
        reload: true
      delegate_to: localhost
```

### python script for debugging
```python
import json
import requests

api_key = ''
api_secret = ''
base_url = 'https://opnsense.local/api/wireguard/'

def get_and_print_peers_from_api():
    r = requests.get(base_url+'client/get', auth=(api_key, api_secret))
    for k,v in json.loads(r.text)['client']['clients']['client'].items():
        if v['name'].startswith('TEST_'):
            print(f" - {v['name']}")

def add_peer(name):
    data = {
        "client": {"name": name,
                   "enabled": 1,
                   "pubkey": "Rk9PQkFSCg==",
                   "serverport": 51820,
                   "tunneladdress": "127.0.0.1",
                   "serveraddress": "127.0.0.1",
                   "keepalive": 25
                   }
            }
    r = requests.post(base_url+'client/addClient', json=data, auth=(api_key, api_secret))
    print(r)

print('Initial config:')
get_and_print_peers_from_api()

for host in ['TEST_host1', 'TEST_host2', 'TEST_host3', 'TEST_host4']:
    print('')
    print(f'adding host {host}')
    add_peer(host)
    print('')
    print('hosts present in api:')
    get_and_print_peers_from_api()
```

**Comment by mnlhfr** [comment]
been trying to debug this a little further and from time to time this completely crashes my opnsense appliance with a kernel panic, so there is for sure something not accounted for on their side.

I set up a clean opnsense VM with just wireguard installed and active in order to rule out any funky config related issues on my end and am able to reproduce this on the fresh environment as well...

Unfortunately i am not too familiar with ansible yet. Especially when it comes to how it actually does execute the tasks etc. When running the playbook with `-vvv` i noticed that it appears to send the api requests in parallel, which led me to try the `serial: 1` parameter in my playbook, which sets the execution batchsize to 1. Using this method, everything works as expected, but it significantly slows down the playbook for obvious reasons.

I am wondering if and how this could be solved in the plugin. It really just seems to trigger the issue on opnsense when its literally executed in parallel, because executing it sequentially like in the python script i provided, doesn't cause any of these issues. I also tried adding the call the reconfigure endpoint to see if this might be the culprit, but no issues as long as its not sent in parallel.

**Comment by ansibleguy** [comment]
Greetings.

I'll try to reproduce the issue.
I find it interesting that [the test-cases for WireGuard peers](https://github.com/ansibleguy/collection_opnsense/blob/latest/tests/wireguard_peer.yml) work as expected (also adding multiple ones)

**Comment by ansibleguy** [comment]
Could you please try to re-run the task with `reload: false` set?
I could imagine the OPNSense service would discard data if this action is performed multiple times simultaneously.
It essentially performs the same action as clicking on the 'Apply' button in the WebUI.
But don't forget - you will have to [reload the config later on](https://opnsense.ansibleguy.net/en/latest/modules/2_reload.html):
```yaml
  - name: Applying wireguard config
    ansibleguy.opnsense.reload:
      target: 'wireguard'
    when: wg_peers.changed
```

But I don't see any other improvements that could be made on the module-side as the module does not know anything about the 'Ansible Context' (per example that it is called in a loop).

**Comment by mnlhfr** [comment]
unfortunately `reload: false` also doesn't fully resolve the issue for me. The OPNSense API just doesn't seem to do too well with multiple parallel requests adding new entries. 

But as mentioned before I found that `serial: 1` while extremely slow, works as intended and since I'm not adding wireguard peers on a daily basis anyway, I moved everything related to this to a separate playbook and am working around the issue this way.

I also found that OPNSense reliably runs into a kernel panic when hitting the config reload (reconfigure endpoint) in quick succession like it would happen with this plugin when adding a number of peers at once. I contacted OPNSense about it and here is the relevant part of their response for reference:
```
Wireguard is a community plugin, you could add a ticket on our GitHub https://github.com/opnsense/plugins/issues, but it given this crashes somewhere in the kernel, it could also be hardware or driver related. 

(To be honest, I don’t think it’s a very good idea to reconfigure wireguard that many times in a parallel loop, but that’s a different story)
```

I still need to create that ticket for them. In regards to it being a hardware issue, I find that hard to believe tbh. since it is 100% reproducible on both a fresh virtual machine install as well as on my desktop appliance that I bought from the official opnsense shop. But who knows.

Anyway, thanks for your effort!
